###user registration

post http://localhost:4000/user-api/user
Content-Type: application/json

{
    "userType":"user",
    "username":"ravikiran_04",
    "password":"raja",
    "email":"ravi04@gmail.com"
}

###user login

post http://localhost:4000/user-api/login
Content-Type: application/json

{
    "userType":"user",
    "username":"ravikiran_04",
    "password":"raja"

}

###author registration
post http://localhost:4000/author-api/user
Content-Type: application/json

{
    "userType":"author",
    "username":"shiva_04",
    "password":"shiva",
    "email":"shiva04@gmail.com"
}
###Author login

post http://localhost:4000/author-api/login
Content-Type: application/json

{
    "userType":"author",
    "username":"shiva_04",
    "password":"shiva"
}

###V
post http://localhost:4000/author-api/new-article
Content-Type: application/json

{
    "articleId":"{{$timestamp}}",
    "title":"Fundamentls of JavaScript",
    "category":"programming",
    "content":"JavaScript is a programming language that adds interactivity to your website. This happens in games, in the behavior of responses when buttons are pressed or with data entry on forms; with dynamic styling; with animation, etc. This article helps you get started with JavaScript and furthers your understanding of what is possible.",
    "dateofCreation":"{{$datetime iso8601}}",
    "dateofModification":"{{$datetime iso8601}}",
    "username":"shiva_04",
    "comments":[],
    "status":true
}

//----------------Author operations----------------------------------
### read articles by authors user name
get http://localhost:4000/author-api/articles/shiva_04

### edit articles by authors username
put http://localhost:4000/author-api/article
Content-Type: application/json

{
    "articleId":"1709442721",
    "title":"Fundamentls of JavaScript",
    "category":"programming",
    "content":"that adds interactivity to your website. This happens in games, in the behavior of responses when buttons are pressed or with data entry on forms; with dynamic styling; with animation, etc. This article helps you get started with JavaScript and furthers your understanding of what is possible.",
    "dateofCreation":"2024-03-03T05:12:01.423Z",
    "dateofModification":"{{$datetime iso8601}}",
    "username":"shiva_04",
    "comments":[],
    "status":true
}

### Delete articles by authors using soft delete(i.e Hide data by updatingg status=false)
put http://localhost:4000/author-api/article/1709442721
Content-Type: application/json

{
    "articleId":"1709442721",   
    "title":"Fundamentls of JavaScript",
    "category":"programming",
    "content":"that adds interactivity to your website. This happens in games, in the behavior of responses when buttons are pressed or with data entry on forms; with dynamic styling; with animation, etc. This article helps you get started with JavaScript and furthers your understanding of what is possible.",
    "dateofCreation":"2024-03-03T05:12:01.423Z",
    "dateofModification":"2024-03-03T05:47:42.592Z",
    "username":"shiva_04",
    "comments":[],
    "status":false
}


//--------------------------------User operations---------------------------
### Read all articles 
get http://localhost:4000/user-api/articles


### Write comment by User

POST http://localhost:4000/user-api/comment/1709442721
Content-Type: application/json

{
    "username":"ravi_04",
    "comment":"Amazing"
}
